### ISSUE TITLE
Patchwork is pretty CPU intensive while idling

### ISSUE THREAD

**Issue by jrf0110** [ssbc/patchwork#30]
![Activity Monitor](http://storage.j0.hn/Screen%20Shot%202015-09-29%20at%204.51.36%20PM.png)

This might be a limitation of Node Webkit, but is there anything we can do about this? I have noticeable performance issues in other apps while Patchwork is open :(

**Comment by pfraze** [comment]
Oh wow, that's brutal. I'm seeing the same thing. Going to diagnose.

**Comment by dominictarr** [comment]
does scuttlebot have the same thing? if so can you disable plugins until it goes away?

**Comment by pfraze** [comment]
thats what I'm going to try, starting with the gossip plugin

**Comment by pfraze** [comment]
It's the animated gifs and webms. In `./ui/lib/markdown.js#renderer.image` you can disable the embeds and resolve the issue completely.

The animated gifs are separate from webms, and they are just as intensive. (I'm able to test this thanks to david's p2p gif.)

**Comment by pfraze** [comment]
Yeah, it's the animation. Pausing the videos and hiding the gifs solves it. (Thankfully, setting visibility to hidden fixes the gifs, so the layout wont have to reflow.)

I'll have to watch element visibility and enable/disable as you scroll (darn!)

**Comment by pfraze** [comment]
fixed in https://github.com/ssbc/patchwork/commit/f929c75311e096f232a7933fdbea57d288861cb0

**Comment by gardner** [comment]
I'm still seeing this:

on my linux vps:
<img width="1410" alt="screen shot 2016-03-04 at 9 33 18 am" src="https://cloud.githubusercontent.com/assets/787026/13517710/1c1e37f8-e22b-11e5-8a84-43a3ba4ec07e.png">

on my 8 core mac:
![screen shot 2016-03-04 at 5 04 33 pm](https://cloud.githubusercontent.com/assets/787026/13517724/369d9a24-e22b-11e5-88b2-bb62997ccc14.png)

**Comment by dominictarr** [comment]
@gardner what version are you on? I'm trying to figure out what causes this. but am having trouble reproducing.

**Comment by pfraze** [comment]
@gardner this is an old thread, that correctly diagnosed a different CPU over-use bug in the Patchwork frontend. We're working on what you're experiencing now

**Comment by gardner** [comment]
scuttlebot@drinkbot:~$ sbot version
7.5.2

Should I open a new issue for this? I don't seem to get anything useful when I run it under the profiler...


    note @kOK REPL @uRECWB4KIeKoNMis2UYWyB2aQPvWmS3OePQvBj2zClg=.ed25519 success
      "Feeds updated: 1, New messages: 1"
    note @kOK REPL @hGd3sjghbrkVaFEMUrXV11m2oyKLfLqJQcadvapH02w=.ed25519 success
      "Feeds updated: 1, New messages: 1"
    note @kOK REPL @hGd3sjghbrkVaFEMUrXV11m2oyKLfLqJQcadvapH02w=.ed25519 success
      "Feeds updated: 1, New messages: 1"
    note @kOK REPL @0GLMsG6IgXdv+GjG0U5UnZlwxHnomlfmrlWugx8i4dg=.ed25519 success
      "Feeds updated: 1, New messages: 1"
    note @kOK REPL @hxGxqPrplLjRG2vtjQL87abX4QKqeLgCwQpS730nNwE=.ed25519 success
      "Feeds updated: 1, New messages: 1"
    note @kOK REPL @/02iw6SFEPIHl8nMkYSwcCgRWxiG6VP547Wcp1NW8Bo=.ed25519 success
      "Feeds updated: 1, New messages: 1"
    note @kOK REPL @uRECWB4KIeKoNMis2UYWyB2aQPvWmS3OePQvBj2zClg=.ed25519 success
      "Feeds updated: 1, New messages: 1"
    note @kOK REPL @uRECWB4KIeKoNMis2UYWyB2aQPvWmS3OePQvBj2zClg=.ed25519 success
      "Feeds updated: 1, New messages: 1"
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync
    Device sleep detected, triggering pub sync

**Comment by gardner** [comment]
BTW this is running on a VPS and was installed via ``npm install``.

``uname -a``
Linux drinkbot 2.6.32-042stab113.11 #1 SMP Fri Dec 18 17:32:04 MSK 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by pfraze** [comment]
Let's say https://github.com/ssbc/scuttlebot/issues/270 is our canonical thread for backend CPU usage issues

**Comment by dominictarr** [comment]
@gardner we had a bug in the quota system.. we are still deciding what to do about this, but for now if you run sbot in "party" mode, it will disable that, and shouldn't have this problem. `ssb_party=1 sbot server` will do it.

**Comment by dominictarr** [comment]
or set `"party": true` in `~/.ssb/config`

**Comment by gardner** [comment]
I'm not sure if the party is happening. Is the `.ssb/config` file a json file?

    scuttlebot@stormcloud:~$ cat .ssb/config 
    "party": true
    scuttlebot@stormcloud:~$ 


![screen shot 2016-03-17 at 10 16 50 am](https://cloud.githubusercontent.com/assets/787026/13828988/6ce8c9ac-ec29-11e5-8a19-a1de00ced4e5.png)

**Comment by pfraze** [comment]
@gardner config is a JSON file, it should be
```
{"party": true}
```

**Comment by dominictarr** [comment]
note, you need to be running at least scuttlebot@7.6.0 for this party mode to work.

**Comment by gardner** [comment]
Thanks guys! ``{"party": true}`` in my config file has fixed the cpu utilization problem that I was having. This process has been running for 2 days and only utilized 3.5 hours cpu:
 
<img width="840" alt="screen shot 2016-03-20 at 9 39 00 am" src="https://cloud.githubusercontent.com/assets/787026/13901164/9f0a176c-ee7f-11e5-973f-fd551784fba6.png">

**Comment by pfraze** [comment]
That's good to hear, thanks for the update
