### ISSUE TITLE
Cannot connect to SSB

### ISSUE THREAD

**Issue by richardofortune** [ssbc/patchwork#673]
Getting this error when I try to use any pub invite code. I suspect it's a network block on my work machine. I don't have the skills to determine if this is true, so raising this as a request for advice.
 running OSX (PW 3.8.0 - but has been the case for all previous versions) 

Halp! 

<img width="1037" alt="screen shot 2017-11-17 at 1 40 14 pm" src="https://user-images.githubusercontent.com/418580/32923644-94bb1aa2-cb9d-11e7-9c5c-be8e54672871.png">

**Comment by mmckegg** [comment]
Have you tried other pub invites? Do you get the same error for all of them?

**Comment by richardofortune** [comment]
Yup - I've tried mix's one and dominics one. (they work fine on my machine at home). It could be a security setting applied on the Mac by our it team. As I can't even connect when using my own wifi. Just wondering if you had any ideas what they could be blocking? Or whether there are verbose logs I can check to see what's happening on the Patchwork side

**Comment by mmckegg** [comment]
Patchwork uses TCP 8008 for pretty much everything. It also uses UDB 8008 for local peer discovery. Are you able to see it from another machine running patchwork on the same network?

If you run from command line with `--logging.level info`, it will give you more info about connection status/failure. If you are building from source use `npm start -- --logging.level info`.

I still suspect it could just be that those pubs are busy/down. That tends to happen from time to time. Though, if you can't see a local patchwork running on the same network, then there might be some kind of problem.

**Comment by seafox** [comment]
@richardofortune did you find a solution? I'm experiencing the same on Arch, with log info flag on:
"error": "Error: connect ECONNREFUSED 81.201.60.131:8008\n    at Object.exports._errnoException (util.js:1024:11)\n    at exports._exceptionWithHostPort (util.js:1047:20)\n    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1150:14)",
    "failure": 6
  }
....... 
 "Negotiation Error (1)"
info @mnv SBOT pub.lua.cz:8008@xYSW6eVu8gTS/nTSXZiH97dgKZ+wp7NkomR6WKK/PBI=.ed25519 connection failed
  "connect ECONNREFUSED 81.201.60.131:8008"

**Comment by richardofortune** [comment]
Only getting back to this issue now. Glad you got it sorted @seafox !

**Comment by dhornbein** [comment]
I'm having the same error on OSX `10.12.6`

**Comment by christianbundy** [comment]
Getting the same error on Debian GNU/Linux 9.3 (stretch), but was able to connect to ssb.ekata.social after repeatedly clicking "redeem invite".

```console
$ npm start -- --logging.level info

> ssb-patchwork@3.8.10 start /home/christianbundy/patchwork
> electron index.js "--logging.level" "info"

{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  path: '/home/christianbundy/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'info' },
  blobsPort: 7777,
  server: true,
  _: [] }
Log level: info
git-ssb is not installed, or not available in path
RELOAD 2 1
0 262152 65536 262152
RELOADED 1
SHS:CONNECT shs:OljlObvirD+w+34Mi2powmYBXjJoi3lYU3msirMB3hQ=
SHS:CONNECT shs:OljlObvirD+w+34Mi2powmYBXjJoi3lYU3msirMB3hQ=
info @Olj SBOT net:ssb.ekata.social:8008~shs:XXX CONNECT
  "net:ssb.ekata.social:8008~shs:XXX"
info @Olj SBOT ssb.ekata.social:8008@XXX.ed25519 connection failed
  "challenge not accepted"
{ message: 'challenge not accepted',
  name: 'Error',
  stack: 'Error: challenge not accepted\n    at abort (/home/christianbundy/patchwork/node_modules/secret-handshake/protocol.js:36:45)\n    at Object.cb (/home/christianbundy/patchwork/node_modules/secret-handshake/protocol.js:42:24)\n    at drain (/home/christianbundy/patchwork/node_modules/pull-reader/index.js:42:23)\n    at /home/christianbundy/patchwork/node_modules/pull-reader/index.js:59:18\n    at /home/christianbundy/patchwork/node_modules/pull-reader/index.js:20:7\n    at /home/christianbundy/patchwork/node_modules/pull-stream/throughs/through.js:19:9\n    at drain (/home/christianbundy/patchwork/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/home/christianbundy/patchwork/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:120:20)\n    at Socket.emit (events.js:210:7)' }
info @Olj SBOT net:ssb.ekata.social:8008~shs:XXX CONNECT
  "net:ssb.ekata.social:8008~shs:XXX"
info @Olj SBOT ssb.ekata.social:8008@XXX.ed25519 connection failed
  "challenge not accepted"
{ message: 'challenge not accepted',
  name: 'Error',
  stack: 'Error: challenge not accepted\n    at abort (/home/christianbundy/patchwork/node_modules/secret-handshake/protocol.js:36:45)\n    at Object.cb (/home/christianbundy/patchwork/node_modules/secret-handshake/protocol.js:42:24)\n    at drain (/home/christianbundy/patchwork/node_modules/pull-reader/index.js:42:23)\n    at /home/christianbundy/patchwork/node_modules/pull-reader/index.js:59:18\n    at /home/christianbundy/patchwork/node_modules/pull-reader/index.js:20:7\n    at /home/christianbundy/patchwork/node_modules/pull-stream/throughs/through.js:19:9\n    at drain (/home/christianbundy/patchwork/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/home/christianbundy/patchwork/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:120:20)\n    at Socket.emit (events.js:210:7)' }
^[info @Olj SBOT net:ssb.ekata.social:8008~shs:XXX CONNECT
  "net:ssb.ekata.social:8008~shs:XXX"
SHS:CONNECT shs:XXX
SHS:CONNECT shs:XXX
info @Olj SBOT ssb.ekata.social:8008:@XXX.ed25519 Connected
{ key: '%iJdi6aAmL+uw0eS4StTaBrkpGHI7cVzXy4JP1RRlFyw=.sha256',
  value: 
   { previous: '%yzjcMRf5pZE+FMKysuwjjBbMDzxs6+7JqJAKwKXzaPs=.sha256',
     author: '@OljlObvirD+w+34Mi2powmYBXjJoi3lYU3msirMB3hQ=.ed25519',
     sequence: 2,
     timestamp: 1519856747047,
     hash: 'sha256',
     content: { type: 'pub', address: [Object] },
     signature: 'M/hJAmmY/zR3EMxmO4M+Dgn0alOhqvkr3yrcytmjWJ0T9W6uZzAdapc02wclE/46FlMcr68q9bnZB4S50pdGBg==.sig.ed25519' },
  timestamp: 1519856747093.001 }
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
skip gossip
```

I've redacted my invite code, but the `XXX` bit was a single invite code that didn't change.

**Comment by christianbundy** [comment]
Not sure, honestly, my best guess is that it's running a different version of ssb-server. Happy to hear that this was resolved!

**Comment by patrickbolle** [comment]
Hi folks. I'm still encountering this bug on the newest Patchwork version.

Logs from using the above debug info command:

```
installed: X-AppImage-BuildId=c5ceb290-e2f6-11a8-07c2-b1ba5ffda287 image: X-AppImage-Bu
{ party: true,
  host: '',
  port: 8008,
  timeout: 0,
  pub: true,
  local: true,
  friends: { dunbar: 150, hops: 2 },
  ws: { port: 8989 },
  gossip: { connections: 3 },
  connections: { incoming: { net: [Array] }, outgoing: { net: [Array] } },
  path: '/home/patrick/.ssb',
  timers: { connection: 0, reconnect: 5000, ping: 300000, handshake: 5000 },
  caps: 
   { shs: '1KHLiKZvAvjbY1ziZEHMXawbCEIM6qwjCDm3VYRan/s=',
     sign: null },
  master: [],
  logging: { level: 'notice' },
  blobsPort: 8989,
  server: true,
  _: [ 'info' ] }
ssb-friends: createFriendStream legacy api used
git-ssb is not installed, or not available in path
SHS:CONNECT shs:JUBGIPQ3KzZEqc03FX53bZucL9i/UqgHQgpPyJHPzpw=
ssb-friends: stream legacy api used
ssb-friends: get legacy api used
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
{ message: 'challenge not accepted',
  name: 'Error',
  stack: 'Error: challenge not accepted\n    at abort (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/secret-handshake/protocol.js:36:45)\n    at Object.cb (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/secret-handshake/protocol.js:42:24)\n    at drain (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/pull-reader/index.js:42:23)\n    at /tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/pull-reader/index.js:59:18\n    at /tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/pull-reader/index.js:20:7\n    at drain (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/stream-to-pull-stream/index.js:141:18)\n    at Socket.<anonymous> (/tmp/.mount_PatchwDgDJam/app/resources/app.asar/node_modules/stream-to-pull-stream/index.js:162:5)\n    at emitOne (events.js:121:20)\n    at Socket.emit (events.js:211:7)\n    at TCP._handle.close [as _onclose] (net.js:554:12)' }
```

Can't connect to any of the public pubs listed on Scuttlebutt.nz - and besides that I've been having issues with Patchwork not loading any new posts over the past week or so. 

See %C2FsGWK+IGxR23IZIC0+7Msf7iTf9HN/tlzFWVSOqtU=.sha256 for original post about this a few days back.

Debian Stretch as well.

**Comment by christianbundy** [comment]
Hey @patrickbolle, would you mind opening a new issue for this? It'd also be helpful to know which pubs you're trying to connect to, that way we can try to reproduce the problem exactly.

**Comment by patrickbolle** [comment]
@christianbundy Absolutely. Thanks!
